spring.application.name: SaltEdgeClientAPI
spring.profiles.active: local
server:
  port: 0

#Configuration Manager
spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

#Service Discovery Eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true